print("Welcome to mit liscence compiler!")
print("Input the year")
year = int(input())
print("Input the copyrigth owner!")
copy_owner = input()
print("Input the name of the softwere!")
softwere_name = input()

year_str = str(year)
print(f"Copyright (c) {year_str} {copy_owner}")
print("Permission is hereby granted, free of charge, to any person")
print("obtaining a copy of this software and associated documentation")
print(f"files for {softwere_name}, to deal in the Software without")
print("restriction, including without limitation the rights to use,")
print("copy, modify, merge, publish, distribute, sublicense, and/or sell")
print("copies of the Software, and to permit persons to whom the")
print("Software is furnished to do so, subject to the following conditions:")
print("")
print("The above copyright notice and this permission notice shall be")
print("included in all copies or substantial portions of the Software.")
print("")
print("THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND,")
print("EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES")
print("OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND")
print("NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT")
print("HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,")
print("WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING")
print("FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR")
print("OTHER DEALINGS IN THE SOFTWARE.")